os: linux
language: generic

services:
  - docker

install:
  - ls client
  - docker-compose build test
script:
  - docker-compose up test

before_deploy:
  - docker -t cabemo/multi_nginx build nginx ./nginx
  - docker -t cabemo/multi_client build client ./client
  - docker -t cabemo/multi_test build test ./test
  - docker -t cabemo/multi_api build api ./api
  - docker -t cabemo/multi_worker build worker ./worker

after_success:
  - docker-compose build
  - echo $DH_PASS | docker login -u $DH_USER --password-stdin
  - docker push $DH_USER/multi_nginx
  - docker push $DH_USER/multi_client
  - docker push $DH_USER/multi_test
  - docker push $DH_USER/multi_api
  - docker push $DH_USER/multi_worker
